BraniacLMS/urls.py
from django import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/',include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

authapp/urls.py
from authapp.apps import AuthappConfig
from django.urls import path
from authapp.views import CustomLoginView, RegisterView, CustomLogoutView, EditView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('Edit/', EditView.as_view(), name='edit'),
]

mainapp/urls.py
from mainapp import views
from django.urls import path
from mainapp.apps import MainappConfig


app_name = MainappConfig.name

urlpatterns = [

    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('courses/', views.CoursesListView.as_view(), name='courses'),
    path('docsite/', views.DocSiteView.as_view(), name='docsite'),
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('news/', views.NewsView.as_view(), name='news'),
    path("news/<int:page>/", views.NewsWithPaginatorView.as_view(),name="news_paginator"),
    

]

mainapp/models.py
from django.db import models

NULLABLE = {'blank':True, 'null':True}

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    deleted = models.BooleanField(default=False, verbose_name='Удален')

    class Meta:
        abstract = True
        ordering = ('-created_at',)

    def delete(self, *args, **kwargs):
        self.deleted = True
        self.save()

class NewsManager (models.Manager):

    def delete(self):
        pass

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)

class News(BaseModel):
    objects = NewsManager

    title = models.CharField(max_length=255, verbose_name='Заголовок')
    preamble = models.CharField(max_length=1000, verbose_name='Вступление')
    body = models.TextField(verbose_name='Содержимое')
    body_as_markdown = models.BooleanField(default=False, verbose_name='Способ разметки')

    def __str__(self):
        return f'#{self.pk} {self.title}'

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'


class Course(BaseModel):
    name = models.CharField(max_length=256, verbose_name="Название курса")
    description = models.TextField(verbose_name="Описание курса", **NULLABLE)
    description_as_markdown = models.BooleanField(verbose_name="Способ разметки", default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Стоимость", default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name="Изображение")

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = 'курсы'


class Lesson(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Номер урока")
    title = models.CharField(max_length=256, verbose_name="Название урока")
    description = models.TextField(verbose_name="Описание урока", **NULLABLE)
    description_as_markdown = models.BooleanField(verbose_name="Способ разметки", default=False)

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    class Meta:
        verbose_name = 'урок'
        verbose_name_plural = 'уроки'
        ordering = ("course", "num")


class CoursesTeacher(BaseModel):
    courses = models.ManyToManyField(Course)
    name_first = models.CharField(max_length=128, verbose_name="Имя")
    name_second = models.CharField(max_length=128, verbose_name="Фамилия")
    day_birth = models.DateField(verbose_name="День рождения")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "{0:0>3} {1} {2}".format(self.pk, self.name_second, self.name_first)

    class Meta:
        verbose_name = 'Учителя курсов'
        verbose_name_plural = 'Учителя курсов'

mainapp/views.py
#from django.shortcuts import render
import json

from django.conf import settings
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.shortcuts import render
from datetime import datetime

# Create your views here.
from mainapp.models import News, Course


class ContactsView(TemplateView):
    template_name = 'mainapp/contacts.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data ['contacts'] = [
            {
                'map' : 'https://yandex.ru/map-widget/v1/-/CCUAZHcrhA',
                'city': 'Санкт‑Петербург',
                'phone': '+7-999-11-11111',
                'email': 'geeklab@spb.ru',
                'address': 'территория Петропавловская крепость, 3Ж'
            },{
                'map' : 'https://yandex.ru/map-widget/v1/-/CCUAZHX3xB',
                'city': 'Казань',
                'phone': '+7-999-22-22222',
                'email': 'geeklab@kz.ru',
                'address': 'территория Кремль, 11, Казань, Республика Татарстан, Россия'
            },{
                'map' : 'https://yandex.ru/map-widget/v1/-/CCUAZHh9kD',
                'city': 'Москва',
                'phone': '+7-999-33-33333',
                'email': 'geeklab@msk.ru',
                'address': 'Красная площадь, 7, Москва, Россия'
            }
        ]

        return context_data


class CoursesListView(TemplateView):
    template_name = 'mainapp/courses_list.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Course.objects.all()
        return context_data

class DocSiteView(TemplateView):
    template_name = 'mainapp/doc_site.html'


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'


class LoginView(TemplateView):
    template_name = 'mainapp/login.html'


class NewsView(TemplateView):
    template_name = 'mainapp/news.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = News.objects.all()
        return context_data


class NewsWithPaginatorView(NewsView):
    def get_context_data(self, page, **kwargs):
        context = super().get_context_data(page=page, **kwargs)
        context["page_num"] = page
        return context

mainapp/templates/mainapp/includes/inc_main_menu.html
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:mainapp.views.NewsView' %}active{% endif %}">
            <a class="nav-link" href="{% url 'mainapp:news' %}">Новости</a>
        </li>
        <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:mainapp.views.CoursesListView' %}active{% endif %} ">
            <a class="nav-link" href="{% url 'mainapp:courses' %}">Курсы</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Профиль
                </a>
                <div class="dropdown-menu" aria-labelledby="ddProfile">
                    <a class="dropdown-item" href="{% url 'authapp:edit' %}">Редактировать профиль</a>
                    <a class="dropdown-item" href="#">Мои курсы</a>
                    <div class="dropdown-divider"></div>
                    {% if user.is_staff %}
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Модерация</a>
                    {% endif %}
                    {% if user.is_superuser %}
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Административный раздел</a>
                    {% endif %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'authapp:logout' %}">Выход</a>
                </div>

            </li>
        {% else %}
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'authapp:login' %}">Вход</a>
            </li>
        {% endif %}
        <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:mainapp.views.ContactsView' %}active{% endif %} ">
            <a class="nav-link" href="{% url 'mainapp:contacts' %}">Контакты</a>
        </li>


    </ul>
    <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
</div>